apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: default
spec:
  secretName: my-certificate-secret
  dnsNames:
    - chaincue.minikube
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
