apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: "https://iam.chaincue.se/auth/realms/blockchain"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: "https://iam.chaincue.se/auth/realms/blockchain/protocol/openid-connect/token"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI: "https://iam.chaincue.se/auth/realms/blockchain/protocol/openid-connect/userinfo"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI: "https://iam.chaincue.se/auth/realms/blockchain/protocol/openid-connect/certs"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_AUTH_METHOD: "header"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USERNAME_ATTR: "preferred_username"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: "chaincue-client"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: "openid"
