apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: chaincue:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-configmap
          resources:
            limits:
              cpu: 2000m
            requests:
              cpu: 1000m
      imagePullSecrets:
        - name: gitlab-registry

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  #  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 30005
