version: '3.9'
services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
      - ./registry.crt:/certs/registry.crt
      - ./registry.key:/certs/registry.key
      - ./htpasswd:/htpasswd
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/htpasswd
    networks:
      - registry

volumes:
  registry_data:
    name: registry_data
    driver: local

networks:
  registry:
    name: registry
    driver: bridge
