apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: postgres-standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-backend
spec:
  serviceName: postgres-backend-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-backend
  template:
    metadata:
      labels:
        app: postgres-backend
    spec:
      containers:
        - name: postgres-backend
          image: postgres:15.3
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
          ports:
            - containerPort: 5432
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        storageClassName: postgres-standard
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-backend-service
spec:
  clusterIP: None
  selector:
    app: postgres-backend
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
