# Vault
version: "3.9"

services:
  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault-1
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK

  postgres_kc_09_26_23:
    container_name: postgres_kc_09_26_23
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_kc_09_26_23:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_DB
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    networks:
      - chaincue_tech_net

  keycloak_09_26_23:
    container_name: keycloak_09_26_23
    image: quay.io/keycloak/keycloak:22.0
    command: [ "start" ]
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_kc_09_26_23
      KC_DB_URL_DATABASE: keycloak_DB
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: POSTGRES_PASSWORD
      KC_DB_SCHEMA: public
      KC_HOSTNAME: localhost
      KC_HOSTNAME_ADMIN: localhost
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/localhost.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/localhost.key
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./certs:/etc/x509/https
    depends_on:
      - postgres_kc_09_26_23
    networks:
      - chaincue_tech_net

volumes:
  postgres_data_kc_09_26_23:
    name: postgres_data_kc_09_26_23
  pgadmin_data_09_26_23:
    name: pgadmin_data_09_26_23

networks:
  chaincue_tech_net:
    name: chaincue_tech_net
    driver: bridge
